### ISSUE TITLE
Allow to subscribe to specific channels

### ISSUE THREAD

**Issue by Zoriot** [Zechiax/Asterion#157]
I think everyone would benefit from that. Also, it shouldn't be that hard to implement that. [
Modrinth Site with many pushes to the beta channel.](https://modrinth.com/plugin/viaversion/versions)

Can someone pick this up?

**Comment by Zechiax** [comment]
Thanks for the suggestion! I wonder why I never thought of it before. 
I'll probably have a look at it over the weekend, it shouldn't be hard, just need to add a new setting per project.

**Comment by Zoriot** [comment]
Thanks, that would be soo nice 🤩.
It would be nice to allow also only updates for a specific platform, like ``paper``.

**Comment by Zechiax** [comment]
That would also be a nice addition. I have added a separate issue (#159) to track that. I'm not sure how hard it would be to implement, but I'll try to look into it.

**Comment by Zechiax** [comment]
Implementation done in #160, will build and publish the version in a few moments, should be live in around 30 minutes. 
You can configure the filters using `/entry {project_id}` command through a select menu. Let me know if there are any problems with the filtering or you have any other suggestion! :)
