### ISSUE TITLE
Filter subscription by loader type (Fabric, Paper, ...)

### ISSUE THREAD

**Issue by Zechiax** [Zechiax/Asterion#159]

**Comment by Zoriot** [comment]
Do you know when you have time to implement that? 
If it's not possible in the near future I would try it myself

**Comment by Zechiax** [comment]
I have some spare time today, will see what I can do today! 😁

I think the best solution would be to have a global settings and per project override As Discord servers with paper used to host the MC server will probably not use Forge mods etc, so I'll try to make it like this.

**Comment by Zoriot** [comment]
Sounds really great. 💯
Idk how complicated this global setting is, for now it would be okay too (for me) to only set if afterwards like it’s with the Release Type currently. 
 _Then implement the global thing later on. Maybe also the same for release type - I think it would make sense there too_

**Comment by Zechiax** [comment]
Yeah, that sounds sensible for now, as the global settings would probably have to be for project types (mods, plugins, shaders, ..) as they have different loader types, so the current implementation will be per entry.
I'll make the global ones separate issues after this one is solved.

**Comment by Zechiax** [comment]
The feature is live on the public instance. Let me know if you encounter any problems! 😊

It's configurable in the /entry <project_id> embed
