### ISSUE TITLE
Add Source Code Link

### ISSUE THREAD

**Issue by Zoriot** [Zechiax/Asterion#161]
Sometimes you just want to Jump to the repo...

On the Site it's in the Description Tab on the Bottom -> Links -> View Source

**Comment by Zechiax** [comment]
Just to be sure, are you reffering to the Wiki site here: [https://zechiax.gitbook.io/asterion](https://zechiax.gitbook.io/asterion)?

**Comment by Zoriot** [comment]
> Just to be sure, are you reffering to the Wiki site here: https://zechiax.gitbook.io/asterion?

Oh no, I meant on the Plugin Update embed the Bots sends if you subscribe for a project.

**Comment by Zechiax** [comment]
Ahh gotcha! That should be pretty straighforward to implement. 

For my future reference, just need to add a new item here (if project has source URL): https://github.com/Zechiax/Asterion/blob/98b6d9d7c7c10aeb0f235744b6be71e3abb43318/Asterion/EmbedBuilders/ModrinthEmbedBuilder.cs#L286-L292

**Comment by Zechiax** [comment]
Implemented in #165, will deploy after I test that it works as expected

**Comment by Zoriot** [comment]
> Implemented in #165, will deploy after I test that it works as expected

Doesn't work for me. It is still not shown.
